# Generated by Django 4.2.3 on 2023-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VoltAutoApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
