# Generated by Django 4.2.3 on 2023-07-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VoltAutoApp", "0002_automaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="automaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VoltAutoApp.automaker",
            ),
        ),
    ]
