# Generated by Django 4.2.3 on 2023-07-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VoltAutoApp", "0003_car_automaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="automaker",
        ),
        migrations.AddField(
            model_name="car",
            name="battery_capacity",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="range_per_charge",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "automaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VoltAutoApp.automaker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VoltAutoApp.carmodel",
            ),
        ),
    ]
