# Generated by Django 4.2.3 on 2023-07-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "VoltAutoApp",
            "0004_remove_car_automaker_car_battery_capacity_car_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="automaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VoltAutoApp.automaker",
            ),
        ),
    ]
