# Generated by Django 4.2.3 on 2023-07-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VoltAutoApp", "0005_car_automaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="VoltAutoApp.car",
            ),
        ),
    ]
